[[colors.indexed_colors]]
color = "#101a23"
index = 232

[[colors.indexed_colors]]
color = "#1a2632"
index = 233

[[colors.indexed_colors]]
color = "#243242"
index = 234

[[colors.indexed_colors]]
color = "#2e3e51"
index = 235

[[colors.indexed_colors]]
color = "#394a60"
index = 236

[[colors.indexed_colors]]
color = "#435470"
index = 237

[[colors.indexed_colors]]
color = "#4d5e7f"
index = 238

[[colors.indexed_colors]]
color = "#57688e"
index = 239

[[colors.indexed_colors]]
color = "#4d5e7f"
index = 240

[[colors.indexed_colors]]
color = "#61729e"
index = 241

[[colors.indexed_colors]]
color = "#7081a8"
index = 242

[[colors.indexed_colors]]
color = "#8091b2"
index = 243

[[colors.indexed_colors]]
color = "#8fa0bd"
index = 244

[[colors.indexed_colors]]
color = "#9eafc7"
index = 245

[[colors.indexed_colors]]
color = "#adbed1"
index = 246

[[colors.indexed_colors]]
color = "#bdcddb"
index = 247

[[colors.indexed_colors]]
color = "#ccdae5"
index = 248

[[colors.indexed_colors]]
color = "#ccdae5"
index = 249

[[colors.indexed_colors]]
color = "#ccdae5"
index = 250

[[colors.indexed_colors]]
color = "#ccdae5"
index = 251

[[colors.indexed_colors]]
color = "#ccdae5"
index = 252

[[colors.indexed_colors]]
color = "#ccdae5"
index = 253

[[colors.indexed_colors]]
color = "#ccdae5"
index = 254

[[colors.indexed_colors]]
color = "#ccdae5"
index = 255

[colors.bright]
black = "#4d5e7f"
blue = "#90b1ea"
cyan = "#8be9df"
green = "#29d697"
magenta = "#f48aec"
red = "#f9807b"
white = "#ffffff"
yellow = "#f4b74d"

[colors.cursor]
cursor = "#ffffff"
text = "#101a23"

[colors.normal]
black = "#101a23"
blue = "#5389e4"
cyan = "#2cb4a9"
green = "#10a86c"
magenta = "#f430da"
red = "#f45752"
white = "#8091b2"
yellow = "#f67d22"

[colors.primary]
background = "#101a23"
foreground = "#ffffff"
