" load Vundle settings
source ~/.dotfiles/vim/rcs/vundle

" load Markdown settings
source ~/.dotfiles/vim/rcs/plugin-markdown

" load Matchparen settings
source ~/.dotfiles/vim/rcs/plugin-matchparen

" load NERDTree settings
" source ~/.dotfiles/vim/rcs/plugin-nerdtree

" load AutoPairs settings
" source ~/.dotfiles/vim/rcs/plugin-auto-pairs

" load Rust settings
source ~/.dotfiles/vim/rcs/plugin-rust

" load Tagbar settings
source ~/.dotfiles/vim/rcs/plugin-tagbar

" load Unite settings
" source ~/.dotfiles/vim/rcs/plugin-unite

" load Denite settings
source ~/.dotfiles/vim/rcs/plugin-denite

" load Vimfiler settings
" source ~/.dotfiles/vim/rcs/plugin-vimfiler

" load a colorscheme
source ~/.dotfiles/vim/rcs/colorscheme

" load markdown colorscheme edits
source ~/.dotfiles/vim/rcs/colorscheme-markdown

" load auto command settings
source ~/.dotfiles/vim/rcs/autocmd

" load cursor settings
source ~/.dotfiles/vim/rcs/cursor

" load commands
source ~/.dotfiles/vim/rcs/commands

" load kebindings
source ~/.dotfiles/vim/rcs/keybindings
" source ~/.dotfiles/vim/rcs/keybindings-russian

" load omni-completion settings
source ~/.dotfiles/vim/rcs/omni-completion

" load the status line configuration
source ~/.dotfiles/vim/rcs/statusline

" load general settings
source ~/.dotfiles/vim/rcs/general

" vim: textwidth=80 colorcolumn=80:
