#! /usr/bin/env zsh

#[maybe_unused]
declare -a args=($@)

function main TRAPEXIT {
  cd $HOME/.data-upper/pm
  mux start --detached --name=organizer organizer

  cd $HOME/.data-upper/artifacts
  mux start --detached --name=notes notes

  cd $HOME/.dotfiles
  mux start --detached --name=dotfiles simple

  cd $HOME/.lingo
  mux start --detached --name=lingo lingo

  cd $HOME/.development/summaries
  mux start --detached --name=summaries simple

  cd $HOME/.development/sample_media_player
  mux start --detached --name=sample_media_player cpp

  cd $HOME/.desktop
  mux start --detached --name=console console

  tmux attach-session -t console
}

