# ~/.config/mpv/mpv.conf

##
## Set the video output drivers
##
## [mpv.io](https://mpv.io/manual/stable/#video-output-drivers)
##
vo=gpu

#
# Set the initial window size to the specified value (WxH) if the size would be
# larger than that value.
#
  autofit-larger=1200x700

#
# Set the startup volume. 0 means silence, 100 means no volume reduction or
# amplification. Negative values can be passed for compatibility, but are
# treated as 0.
#
# Since mpv 0.18.1, this always controls the internal mixer (aka "softvol").
#
  volume=75

keep-open=yes

pause=yes

# set a priority list of subtitle languages
slang=rus,ru

# title=${filename}

title=${media-title}

hwdec=vdpau

# the filter was turned off due to regression after update
# vf=vdpaupp=sharpen=0.7

osd-duration=5000

osd-font='PT Sans Caption'

osd-font-size=30

osd-bold=no

osd-color='#ffffffff'

osd-border-color='#ff000000'

osd-scale-by-window=no

# ignore subtitle styles specified in ass files
# use styles declared here instead
# sub-ass-override=force
sub-ass-override=strip

##
## sub-hinting=<none|light|normal|native>
##
## Set font hinting type. <type> can be:
## none:   hinting (default)
## light:  autohinter, light mode
## normal: autohinter, normal mode
## native: native hinter
##
## Warning
##
## Enabling hinting can lead to mispositioned text (in situations it's supposed
## to match up video background), or reduce the smoothness of animations with
## some badly authored ASS scripts. It is recommended to not use this option,
## unless really needed.
##

# sub-hinting=normal
sub-hinting=native

# sub-font='PT Sans'
# sub-font-size=42
# sub-border-size=3
# sub-bold=no

sub-font='PT Sans Narrow'
sub-font-size=44
sub-spacing=1.8
sub-outline-size=2
sub-bold=no

# sub-outline-style='opaque-box'
# sub-outline-style='outline-and-shadow'
# sub-outline-style='background-box'
# sub-shadow-offset=0

# sub-font='EB Garamond'
# sub-font-size=58
# sub-spacing=1.7
# sub-border-size=2
# sub-bold=no

# sub-font='Lora'
# sub-font-size=48
# sub-spacing=1.0
# sub-border-size=0
# sub-bold=no

# sub-font='Playfair Display'
# sub-font-size=42
# sub-spacing=1.7
# sub-border-size=0
# sub-bold=no

sub-color='#ffffff'
sub-outline-color='#000000'
# sub-back-color='#00ccff'

# sub-pos=100
sub-pos=93

#
# Distance in seconds from the beginning of a chapter within which a backward
# chapter seek will go to the previous chapter (default: 5.0). Past this
# threshold, a backward chapter seek will go to the beginning of the current
# chapter instead. A negative value means always go back to the previous chapter.
#
  chapter-seek-threshold=5.0

# restrict the quality of Youtube videos
ytdl-format=bestvideo[height<=?1080]+bestaudio/best

# ytdl-raw-options=output="%(uploader)s | %(title)s"

# add the HTTPS protocol to the white list to be able to watch Youtube streams
# demuxer-lavf-o=protocol_whitelist=[https]

#
# ::: Profiles :::
# run with `mpv --profile=alsa video.mkv`
#

# [jack]
# audio-device=jack

# [alsa]
# audio-device=alsa

# vim: set textwidth=80 colorcolumn=80:
