
Section "Monitor"

  Identifier "DP-0"

# Option "Position" "0 0"
# Option "LeftOf" "DP2"
  Option "DPMS" "false"
EndSection

Section "Monitor"

  Identifier "DP-2"

# Option "Primary" "true"
# Option "Position" "2560 0"
  Option "DPMS" "false"
EndSection

Section "Monitor"

  Identifier "DP-6"

# Option "Position" "5120 0"
# Option "RightOf" "DP2"
  Option "DPMS" "false"
EndSection

Section "Device"

  Identifier "Device0"

  Option "Monitor-DP-0" "DP-0"
  Option "Monitor-DP-2" "DP-2"
  Option "Monitor-DP-6" "DP-6"

  Driver "nvidia"
EndSection

Section "ServerLayout"

  Identifier "ServerLayout0"

  Option "StandbyTime" "0"
  Option "SuspendTime" "0"
  Option "OffTime"     "0"
  Option "BlankTime"   "0"
EndSection

