
Section "ServerLayout"

  Identifier "ServerLayout0"

  Screen 0 "Screen0" 0 0

  Option "StandbyTime" "0"
  Option "SuspendTime" "0"
  Option "OffTime" "0"
  Option "BlankTime" "0"
EndSection

Section "Monitor"

  Identifier "DP-0"

  VendorName "Unknown"
  ModelName "Fujitsu/ICL 2716IQH-UR"

  HorizSync 223.0 - 223.0
  VertRefresh 48.0 - 100.0

  Option "DPMS" "false"
EndSection

Section "Monitor"

  Identifier "DP-2"

  VendorName "Unknown"
  ModelName "Fujitsu/ICL 2716IQH-UR"

  HorizSync 223.0 - 223.0
  VertRefresh 48.0 - 100.0

  Option "DPMS" "false"
EndSection

Section "Monitor"

  Identifier "DP-6"

  VendorName "Unknown"
  ModelName "Fujitsu/ICL 2716IQH-UR"
  HorizSync 223.0 - 223.0
  VertRefresh 48.0 - 100.0

  Option "DPMS" "false"
EndSection

Section "Device"

  Identifier "Device0"

  Driver "nvidia"

  VendorName "NVIDIA Corporation"
  BoardName "NVIDIA RTX A2000 12GB"

  Option "Monitor-DP-0" "DP-0"
  Option "Monitor-DP-2" "DP-2"
  Option "Monitor-DP-6" "DP-6"
EndSection

Section "Screen"

  Identifier "Screen0"

  Device "Device0"

  Monitor "DP-6"

  DefaultDepth 24

  Option "Stereo" "0"
  Option "nvidiaXineramaInfoOrder" "DP-0"
  Option "metamodes" "DP-6: 2560x1440_100 +0+0, DP-0: 2560x1440_100 +2560+0, DP-2: 2560x1440_100 +5120+0"
  Option "SLI" "Off"
  Option "MultiGPU" "Off"
  Option "BaseMosaic" "off"

  SubSection "Display"
    Depth 24
  EndSubSection
EndSection

