
Section "Monitor"
  Identifier "DP-0"
  Option "Primary" "true"
  Option "DPMS" "false"
EndSection

Section "Monitor"
  Identifier "DP-2"
  Option "LeftOf" "DP-0"
  Option "DPMS" "false"
EndSection

Section "Monitor"
  Identifier "DP-6"
  Option "RightOf" "DP-0"
  Option "DPMS" "false"
EndSection

Section "ServerLayout"
  Identifier "ServerLayout0"
  Option "StandbyTime" "0"
  Option "SuspendTime" "0"
  Option "OffTime" "0"
  Option "BlankTime" "0"
EndSection

