#! /usr/bin/zsh

# To get a scancode and a keycode, currently binded to the scancode,
# run `evtest /dev/input/event0` and then press the corresponding
# key.
#
# For example, by running `evtest /dev/input/event0` and then
# pressing the Escape key, you'll get the following output:
#
# -------------- SYN_REPORT ------------
# type 4 (EV_MSC), code 4 (MSC_SCAN), value 3a
# type 1 (EV_KEY), code 1 (KEY_ESC), value 1
# -------------- SYN_REPORT ------------
# type 4 (EV_MSC), code 4 (MSC_SCAN), value 3a
# type 1 (EV_KEY), code 1 (KEY_ESC), value 0
#
# The `value' from the first line (3a) is the scancode and the `code' from
# the second line (1) is the keycode.

# Change keycodes for scancodes:
#   dd (KEY_COMPOSE)  to 126 (KEY_RIGHTMETA);
#   3a (KEY_CAPSLOCK) to 1   (KEY_ESC);
#   1  (KEY_ESC)      to 58  (KEY_CAPSLOCK)

/usr/bin/setkeycodes dd 126 3a 1 1 58
