#! /usr/bin/env zsh

for i in {0..255} ; do
    # printf "\x1b[38;5;${i}m%3d " "${i}"
    printf "\x1b[48;5;${i}m%-8d" "${i}"

    if (( ($i - 15) % 16 == 0 )) print "\n"

    # if (( $i == 15 )) || (( $i > 15 )) && (( ($i-15) % 12 == 0 )); then
    #     echo;
    # fi
done
