#! /usr/bin/env zsh


url=`xclip -selection 'clipboard' -o`
title=`yt-dlp --skip-download --dump-json --output '%(uploader)s | %(title)s' $url | jshon -e _filename | sed -rn 's/"//gp'`
mpv --geometry=1276x718 --title=$title $url

if [[ error_code=$? -ne 0 ]]; then
  notify-send --app-name=MClip 'MClip' "Cannot play a video file from URL:\n`echo $url | cut -c -40`...\nError: $error_code"
fi
