#! /usr/bin/env zsh


url=`xclip -selection 'clipboard' -o`
title=`youtube-dl --skip-download --dump-json --output '%(uploader)s | %(title)s' $url | jshon -e _filename | sed -rn 's/"//gp'`
mpv --geometry=1276x718 --title=$title $url
