#! /usr/bin/env zsh

case $1 in
  'mount')
    mount /mnt/usb-stick
    notify-send --app-name=usb-stick 'usb-stick was mounted' ;;

  'umount')
    umount /mnt/usb-stick
    notify-send --app-name=usb-stick 'usb-stick was un-mounted' ;;

  *) echo "ERROR: \`usb-stick' was called with no arguments!\nUsage: usb-stick {mount|umount}."
esac
