require 'haml'

task :default => :build

task :build do
  Haml::Options.defaults.merge!(
    :format => :xhtml,
    :autoclose => %w{action separator}
  )

  File.open 'rc.xml', 'w' do |f|
    f.write Haml::Engine.new(File.read 'src/rc.haml').render
  end

  File.open 'menu.xml', 'w' do |f|
    f.write Haml::Engine.new(File.read 'src/menu.haml').render
  end
end
