#
# Path
#

path=(
  /usr/lib/qt6/bin/
  ~/.local/bin
  ~/.cargo/bin
  ~/.opam/5.0.0/bin
  ~/.rvm/bin
  ~/.local/share/vcpkg
  $path
)


# Bootstrap rbenv into the current shell environment
eval "$(rbenv init - --no-rehash zsh)"

