#
# ZSH prompt
#

export PROMPT="%F{10}%B>_%b%f "
export RPROMPT=" %~"

#
# Rubygems
#

export GEM_HOME=$HOME/.gem/ruby/2.5.0

#
# Less
#

export LESS='-F -g -i -M -R -S -w -X -z-4 -#1'

#
# Vim
#

export EDITOR='vim'

#
# User functions
#

export FPATH=$FPATH:$HOME/.local/share/zsh/functions/Zle

#
# Figlet
#

export FIGLET_FONTDIR=$HOME/.local/share/figlet/fonts
