# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename $HOME/.zshrc

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Turn off beep
setopt NO_BEEP

# Set aliases
alias pacman='pacman --color=always'
alias xi="xclip -selection 'clipboard' -i"
alias xo="xclip -selection 'clipboard' -o"
alias mux='tmuxinator'
alias msb="mux start basic $1"
alias mss="mux start simple $1"
alias mdf='cd ~df && mss dotfiles'

# Set the named directories
hash -d pm=$HOME/.data-upper/pm
hash -d df=$HOME/.dotfiles
hash -d dv=$HOME/.development
hash -d pg=$HOME/.development/playground

# Load tmuxinator completions
source ~/.gem/ruby/2.5.0/gems/tmuxinator-0.12.0/completion/tmuxinator.zsh

# Change the standard colors by using terminal control sequences
# Run either of the following to set  the value of color17
# printf "\x1b]4;17;#471009\x7"
# printf "\033]4;17;#471009\007"
