# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename $HOME/.zshrc

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Turn off beep
setopt NO_BEEP

# Set aliases
alias pacman='pacman --color=always'
alias xi="xclip -selection 'clipboard' -i"
alias xo="xclip -selection 'clipboard' -o"
alias mux="tmuxinator"

# Set the named directories
hash -d openbox=$HOME/.config/openbox
hash -d polybar=$HOME/.config/polybar
hash -d pm=$HOME/.data-upper/pm

# Load the Base16 shell configuration
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"
