# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename $HOME/.zshrc

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Set options
# See “The Z Shell Manual”, p. 96, “16 Options” for details

# Turn off beep
setopt no_beep

# Enable extended globbing expressions
# ‘x#’  zero or more occurences of x
# ‘x##’ one or more occurences of x
# ‘^x’  anything not matching x
# ‘x~y’ x but not y
# setopt extended_glob

# Set aliases
alias pacman='pacman --color=always'
alias xi="xclip -selection 'clipboard' -i"
alias xo="xclip -selection 'clipboard' -o"
alias mux='tmuxinator'
alias msb="mux start basic $1 --suppress-tmux-version-warning=SUPPRESS-TMUX-VERSION-WARNING"
alias mss="mux start simple $1 --suppress-tmux-version-warning=SUPPRESS-TMUX-VERSION-WARNING"
alias mdf='cd ~df && mss'
alias mch='cd ~dv/chrome && mss'
alias msc='cd ~ && mux start console --suppress-tmux-version-warning=SUPPRESS-TMUX-VERSION-WARNING'
alias mlg='cd ~lg && mux start lingo --suppress-tmux-version-warning=SUPPRESS-TMUX-VERSION-WARNING'
alias maf='cd ~af && mux start artifacts --suppress-tmux-version-warning=SUPPRESS-TMUX-VERSION-WARNING'
alias mpm='cd ~pm && mux start artifacts --suppress-tmux-version-warning=SUPPRESS-TMUX-VERSION-WARNING'
alias w3m='w3m -B -title'

# Set the named directories
hash -d pm=$HOME/.data-upper/pm
hash -d af=$HOME/.data-upper/artifacts
hash -d df=$HOME/.dotfiles
hash -d dv=$HOME/.development
hash -d pg=$HOME/.development/playground
hash -d lg=$HOME/.documents/lingo
hash -d wo=$HOME/.data-upper/virtualbox/share/work

# Change the standard colors by using terminal control sequences
# Run either of the following to set  the value of color17
# printf "\x1b]4;17;#471009\x7"
# printf "\033]4;17;#471009\007"

# autoload user functions
autoload zle-keymap-select
autoload zle-line-init
autoload fzf-history

# define user widgets
zle -N zle-keymap-select
zle -N zle-line-init
zle -N fzf-history

# define user keybindings
bindkey '^T' fzf-history

# Use an external editor to edit the command line by pressing the `v' key at the edit mode
autoload -U edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# opam configuration
[[ ! -r /home/user/.opam/opam-init/init.zsh ]] || source /home/user/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null

# Load Ruby Version Manager (RVM) into a shell session as a function
source "$HOME/.rvm/scripts/rvm"

# vim: set textwidth=80 colorcolumn=80:
